name: FamJam
favicon: null
layout_spectrum: 0.1885705494787544
typography_spectrum: 0.9084426627960056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8306328449398279
  lightness: 0.30851863347925246
  saturation: 0.7710855782497674
  rhythmicContrast: 0.8917560412082821
purpose: []
